config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  root "posts#index"
  

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order("created_at desc")
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.create!(params[:post].permit(:title, :content))
    redirect_to action: "index"
  end
  
  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "https://tinyurl.com/codesensei" %>
</head>
<body>
  <%= link_to "New post", "/posts/new" %>
  <%= link_to "All posts", "/posts" %>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>
  All posts
</h1>

<% @posts.each do |post| %>
  <h3>
    <%= link_to post.title, post_path(post) %>
  </h3>
<% end %>

app/views/posts/new.html.erb
<h2>
  New post
</h2>

<%= form_for @post do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h2>
  <%= @post.title %>
</h2>

<p>
  <%= @post.content %>
</p>
<p>
  <%= link_to "Share", "https://www.facebook.com/sharer/sharer.php?" + { u: post_url(@post), quote: "Moja pierwsza aplikacja z Code Sensei", title: @post.title }.to_param %>
</p>